'use strict';

/**
 * OpenAPI document → typed fetch client (`client.ts`).
 *
 * The generated file is self-contained TypeScript that:
 *   - imports per-operation request/response types from the types file
 *   - exports `createClient({ baseUrl, fetch?, headers?, onRequest? })`
 *   - returns an object with one async method per operation
 *
 * Per-method signature shape:
 *
 *   await api.getUsersById({ params: { id: '1' }, query: { include: 'posts' } })
 *
 * Keys (`params` / `query` / `body` / `headers`) only appear when the
 * operation declares them. The whole `args` object is optional when nothing
 * is required. Return type is the JSON 2xx response when one is declared,
 * `unknown` otherwise.
 *
 * Errors come back as `DoctreenHttpError` with `status` and the parsed body.
 */

const { operationDescriptors } = require('./operations');

function generateClient(doc, opts) {
  opts = opts || {};
  const typesImportPath = opts.typesImportPath || './types';
  const defaultBaseUrl = opts.baseUrl || '';

  const ops = operationDescriptors(doc);

  // Build the import list from baseName suffixes actually used.
  const importNames = new Set();
  for (const op of ops) {
    if (op.params.path.length > 0) importNames.add(op.baseName + 'Params');
    if (op.params.query.length > 0) importNames.add(op.baseName + 'Query');
    if (op.requestBody) importNames.add(op.baseName + 'Body');
    if (op.response) importNames.add(op.baseName + 'Response');
  }
  const sortedImports = Array.from(importNames).sort();

  const lines = [];
  lines.push('// Generated by `doctreen codegen client`. Do not edit by hand.');
  lines.push('');
  if (sortedImports.length > 0) {
    lines.push('import type {');
    for (let i = 0; i < sortedImports.length; i++) {
      lines.push('  ' + sortedImports[i] + (i < sortedImports.length - 1 ? ',' : ''));
    }
    lines.push('} from ' + JSON.stringify(typesImportPath) + ';');
    lines.push('');
  }

  lines.push('export interface DoctreenClientOptions {');
  lines.push('  baseUrl?: string;');
  lines.push('  fetch?: typeof fetch;');
  lines.push('  headers?: Record<string, string>;');
  lines.push('  onRequest?: (req: { method: string; url: string; init: RequestInit }) => void | Promise<void>;');
  lines.push('}');
  lines.push('');

  lines.push('export class DoctreenHttpError extends Error {');
  lines.push('  readonly status: number;');
  lines.push('  readonly body: unknown;');
  lines.push('  constructor(status: number, body: unknown, message: string) {');
  lines.push('    super(message);');
  lines.push('    this.status = status;');
  lines.push('    this.body = body;');
  lines.push('  }');
  lines.push('}');
  lines.push('');

  lines.push('type RequestInitArgs = {');
  lines.push('  params?: Record<string, unknown>;');
  lines.push('  query?: Record<string, unknown>;');
  lines.push('  body?: unknown;');
  lines.push('  headers?: Record<string, string>;');
  lines.push('};');
  lines.push('');

  lines.push('export function createClient(options: DoctreenClientOptions = {}) {');
  lines.push('  const baseUrl = (options.baseUrl ?? ' + JSON.stringify(defaultBaseUrl) + ').replace(/\\/+$/, "");');
  lines.push('  const _fetch: typeof fetch = options.fetch ?? fetch;');
  lines.push('  const baseHeaders = options.headers ?? {};');
  lines.push('');
  lines.push('  async function request(method: string, rawPath: string, init: RequestInitArgs = {}): Promise<unknown> {');
  lines.push('    let path = rawPath;');
  lines.push('    if (init.params) {');
  lines.push('      for (const k of Object.keys(init.params)) {');
  lines.push('        const v = init.params[k];');
  lines.push('        path = path.replace(":" + k, encodeURIComponent(String(v)))');
  lines.push('                   .replace("{" + k + "}", encodeURIComponent(String(v)));');
  lines.push('      }');
  lines.push('    }');
  lines.push('    if (init.query) {');
  lines.push('      const qs = new URLSearchParams();');
  lines.push('      for (const k of Object.keys(init.query)) {');
  lines.push('        const v = (init.query as Record<string, unknown>)[k];');
  lines.push('        if (v === undefined || v === null) continue;');
  lines.push('        if (Array.isArray(v)) {');
  lines.push('          for (const item of v) qs.append(k, String(item));');
  lines.push('        } else {');
  lines.push('          qs.append(k, String(v));');
  lines.push('        }');
  lines.push('      }');
  lines.push('      const s = qs.toString();');
  lines.push('      if (s) path += (path.indexOf("?") !== -1 ? "&" : "?") + s;');
  lines.push('    }');
  lines.push('    const url = baseUrl + path;');
  lines.push('    const headers: Record<string, string> = Object.assign(');
  lines.push('      { accept: "application/json" },');
  lines.push('      baseHeaders,');
  lines.push('      init.headers || {},');
  lines.push('    );');
  lines.push('    const fetchInit: RequestInit = { method, headers };');
  lines.push('    if (init.body !== undefined) {');
  lines.push('      if (!headers["content-type"] && !headers["Content-Type"]) {');
  lines.push('        headers["content-type"] = "application/json";');
  lines.push('      }');
  lines.push('      fetchInit.body = typeof init.body === "string" ? init.body : JSON.stringify(init.body);');
  lines.push('    }');
  lines.push('    if (options.onRequest) await options.onRequest({ method, url, init: fetchInit });');
  lines.push('    const res = await _fetch(url, fetchInit);');
  lines.push('    const text = await res.text();');
  lines.push('    let parsed: unknown = text;');
  lines.push('    const ct = res.headers.get("content-type") || "";');
  lines.push('    if (text && ct.indexOf("json") !== -1) {');
  lines.push('      try { parsed = JSON.parse(text); } catch { /* keep text */ }');
  lines.push('    } else if (text === "") {');
  lines.push('      parsed = undefined;');
  lines.push('    }');
  lines.push('    if (!res.ok) {');
  lines.push('      throw new DoctreenHttpError(res.status, parsed, method + " " + url + " → " + res.status);');
  lines.push('    }');
  lines.push('    return parsed;');
  lines.push('  }');
  lines.push('');
  lines.push('  return {');
  for (const op of ops) {
    lines.push(emitMethod(op));
  }
  lines.push('  };');
  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

function emitMethod(op) {
  const inputParts = [];
  let hasRequired = false;
  if (op.params.path.length > 0) {
    inputParts.push('params: ' + op.baseName + 'Params');
    hasRequired = true;
  }
  if (op.params.query.length > 0) {
    const anyRequired = op.params.query.some(function (p) { return !!p.required; });
    inputParts.push('query' + (anyRequired ? '' : '?') + ': ' + op.baseName + 'Query');
    if (anyRequired) hasRequired = true;
  }
  if (op.requestBody) {
    const bodyReq = op.requestBody.required;
    inputParts.push('body' + (bodyReq ? '' : '?') + ': ' + op.baseName + 'Body');
    if (bodyReq) hasRequired = true;
  }
  inputParts.push('headers?: Record<string, string>');

  const inputType = '{ ' + inputParts.join('; ') + ' }';
  const argsDecl = hasRequired ? 'args: ' + inputType : 'args: ' + inputType + ' = {}';
  const respType = op.response ? op.baseName + 'Response' : 'unknown';

  // Build the call arg list — only forward keys the op declares.
  // Params/Query are passed through as-is; the runtime only reads them via
  // `String(v)` so we don't need to widen the static types.
  const callKeys = ['headers: args.headers'];
  if (op.params.path.length > 0) callKeys.unshift('params: args.params as unknown as Record<string, unknown>');
  if (op.params.query.length > 0) callKeys.push('query: args.query as unknown as Record<string, unknown> | undefined');
  if (op.requestBody) callKeys.push('body: args.body');

  const callArgs = '{ ' + callKeys.join(', ') + ' }';

  const summary = op.summary ? '    /** ' + op.summary.replace(/\*\//g, '* /') + ' */\n' : '';
  const deprecated = op.deprecated ? '    /** @deprecated */\n' : '';

  return (
    summary + deprecated +
    '    ' + op.fnName + ': (' + argsDecl + ') =>\n' +
    '      request(' + JSON.stringify(op.method) + ', ' + JSON.stringify(op.path) + ', ' + callArgs + ') as Promise<' + respType + '>,'
  );
}

module.exports = { generateClient };
