'use strict';

/**
 * OpenAPI document → TypeScript declaration file (`types.d.ts`).
 *
 * Layout of the emitted file:
 *
 *   1. Header banner
 *   2. `export interface <Name>` for every entry in `components.schemas`
 *      (named schemas — these become reusable interfaces other generated
 *      types reference by name)
 *   3. Per-operation interfaces / type aliases:
 *      - `<Base>Params`   — when the operation has path parameters
 *      - `<Base>Query`    — when the operation has query parameters
 *      - `<Base>Body`     — when the operation has a JSON request body
 *      - `<Base>Response` — when the operation has a JSON 2xx response
 *   4. `export interface Operations` — operation-id → input/output mapping,
 *      used by the generated client as a typed dispatch table.
 *
 * Naming is stable: same OpenAPI doc → same file, byte-for-byte.
 */

const { schemaToTs, createContext, tsIdentifier, safeKey } = require('./openapi-to-ts');
const { operationDescriptors } = require('./operations');

function generateTypes(doc, opts) {
  opts = opts || {};
  const components = (doc.components && doc.components.schemas) || {};
  const ctx = createContext(components);
  const lines = [];

  lines.push('// Generated by `doctreen codegen types`. Do not edit by hand.');
  const info = doc.info || {};
  if (info.title || info.version) {
    lines.push('// Source: ' + (info.title || 'API') + (info.version ? ' v' + info.version : ''));
  }
  lines.push('');

  // 1. Named components.
  const componentNames = Object.keys(components);
  for (const name of componentNames) {
    const id = tsIdentifier(name);
    const ts = schemaToTs(components[name], ctx, 0);
    if (ts.startsWith('{')) {
      lines.push('export interface ' + id + ' ' + ts);
    } else {
      lines.push('export type ' + id + ' = ' + ts + ';');
    }
    lines.push('');
  }

  // 2. Per-operation types.
  const ops = operationDescriptors(doc);
  for (const op of ops) {
    if (op.params.path.length > 0) {
      lines.push('export interface ' + op.baseName + 'Params {');
      for (const p of op.params.path) {
        const t = schemaToTs(p.schema || { type: 'string' }, ctx, 1);
        const optional = p.required === false ? '?' : '';
        lines.push('  ' + safeKey(p.name) + optional + ': ' + t + ';');
      }
      lines.push('}');
      lines.push('');
    }

    if (op.params.query.length > 0) {
      lines.push('export interface ' + op.baseName + 'Query {');
      for (const p of op.params.query) {
        const t = schemaToTs(p.schema || { type: 'string' }, ctx, 1);
        const optional = p.required ? '' : '?';
        lines.push('  ' + safeKey(p.name) + optional + ': ' + t + ';');
      }
      lines.push('}');
      lines.push('');
    }

    if (op.requestBody) {
      const t = schemaToTs(op.requestBody.schema, ctx, 0);
      if (t.startsWith('{')) {
        lines.push('export interface ' + op.baseName + 'Body ' + t);
      } else {
        lines.push('export type ' + op.baseName + 'Body = ' + t + ';');
      }
      lines.push('');
    }

    if (op.response) {
      const t = schemaToTs(op.response.schema, ctx, 0);
      if (t.startsWith('{')) {
        lines.push('export interface ' + op.baseName + 'Response ' + t);
      } else {
        lines.push('export type ' + op.baseName + 'Response = ' + t + ';');
      }
      lines.push('');
    }
  }

  // 3. Operations dispatch table (useful for generic clients).
  if (ops.length > 0) {
    lines.push('export interface Operations {');
    for (const op of ops) {
      const inputParts = [];
      if (op.params.path.length > 0) inputParts.push('params: ' + op.baseName + 'Params');
      if (op.params.query.length > 0) {
        const anyRequired = op.params.query.some(function (p) { return !!p.required; });
        inputParts.push('query' + (anyRequired ? '' : '?') + ': ' + op.baseName + 'Query');
      }
      if (op.requestBody) {
        const bodyReq = op.requestBody.required;
        inputParts.push('body' + (bodyReq ? '' : '?') + ': ' + op.baseName + 'Body');
      }
      const input = inputParts.length > 0 ? '{ ' + inputParts.join('; ') + ' }' : '{}';
      const output = op.response ? op.baseName + 'Response' : 'unknown';
      lines.push('  ' + op.fnName + ': { input: ' + input + '; output: ' + output + ' };');
    }
    lines.push('}');
    lines.push('');
  }

  return lines.join('\n');
}

module.exports = { generateTypes };
